# Generated by Django 3.0.5 on 2020-04-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
                ('user_type', models.CharField(default='student', editable=False, max_length=10, verbose_name='Privilege')),
                ('deleted', models.CharField(default='N', max_length=1, verbose_name='Deactive')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('standard', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('student_contact_no', models.IntegerField(null=True)),
                ('parent_contact_no', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('staffuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Staff Id')),
                ('studentuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Id')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
