# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-27 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'Last Updated On')),
                ('user_type', models.CharField(default=b'student', editable=False, max_length=10, verbose_name=b'Privilege')),
                ('deleted', models.CharField(default=b'N', max_length=1, verbose_name=b'Deactive')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('standard', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('student_contact_no', models.IntegerField(null=True)),
                ('parent_contact_no', models.IntegerField(null=True)),
                ('staffuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name=b'Staff Id')),
                ('studentuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Student Id')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
