# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated On')),
                ('user_type', models.CharField(default='student', editable=False, max_length=10, verbose_name='Privilege')),
                ('deleted', models.CharField(default='N', max_length=1, verbose_name='Deactive')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('staffuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Staff Id')),
                ('studentuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Id')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
