# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='standard',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_contact_no',
            field=models.IntegerField(null=True),
        ),
    ]
