# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
