# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_remove_student_allowregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='staffuser',
        ),
        migrations.AddField(
            model_name='student',
            name='staffuser',
            field=models.ManyToManyField(related_name='staffuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
