# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_auto_20171112_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='staffuser',
        ),
        migrations.AddField(
            model_name='student',
            name='staffuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentuser',
        ),
        migrations.AddField(
            model_name='student',
            name='studentuser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
