# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_auto_20171112_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='staffuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentuser',
        ),
        migrations.AddField(
            model_name='student',
            name='studentuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
