# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20171112_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='student',
            name='deleted',
            field=models.CharField(default='N', max_length=1, verbose_name='Deactive'),
        ),
        migrations.AlterField(
            model_name='student',
            name='staffuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff', verbose_name='Staff Id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student Id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.CharField(default='student', editable=False, max_length=10, verbose_name='Privilege'),
        ),
    ]
