# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20171113_1136'),
        ('students', '0002_student_last_login'),
    ]

    operations = [
    ]
