# Generated by Django 3.0.5 on 2020-04-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowregistration', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(default='staff', editable=False, max_length=10)),
                ('deleted', models.CharField(default='N', max_length=1)),
                ('auto_active_student', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffinstitute', to='institutions.Institutions')),
                ('staffuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'ordering': ('created',),
                'permissions': (('is_staff', 'Friendly permission description'),),
            },
        ),
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=50)),
                ('scl_clg_name', models.CharField(max_length=50)),
                ('std', models.CharField(max_length=10)),
                ('academic_y', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
    ]
