# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=50)),
                ('scl_clg_name', models.CharField(max_length=50)),
                ('std', models.CharField(max_length=10)),
                ('academic_y', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
    ]
