# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='allowregistration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='auto_active_student',
            field=models.BooleanField(default=True),
        ),
    ]
