# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('created',), 'permissions': (('is_staff', 'Friendly permission description'),)},
        ),
    ]
