# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='deleted',
            field=models.CharField(default='N', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_type',
            field=models.CharField(default='staff', editable=False, max_length=10),
        ),
    ]
