# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20180829_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='auto_active_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='allowregistration',
            field=models.BooleanField(default=False),
        ),
    ]
