# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assesments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linked_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.Assesment')),
            ],
        ),
        migrations.CreateModel(
            name='SectionQuestionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.Question')),
                ('for_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.Section')),
            ],
        ),
    ]
