# Generated by Django 3.0.5 on 2020-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20200422_0607'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='for_question',
            field=models.ManyToManyField(to='assesments.Question', verbose_name='Question Mapped To This Section:'),
        ),
    ]
