# Generated by Django 3.0.5 on 2020-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20200422_0607'),
        ('section', '0002_section_for_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='for_question',
            field=models.ManyToManyField(related_name='for_question_all', to='assesments.Question', verbose_name='Question Mapped To This Section:'),
        ),
    ]
