# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('header', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('brief', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_start_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manually')], default='auto', max_length=14)),
                ('total_exam_duration', models.TimeField(null=True)),
                ('total_question', models.IntegerField(default=10)),
                ('privilege', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='private', max_length=14)),
                ('is_exam_active', models.BooleanField(default=True)),
                ('expired_on', models.DateTimeField()),
                ('type', models.CharField(default='assessment', editable=False, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_assesment_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_assesment_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assesments.assesment_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('option_one', models.TextField(max_length=250)),
                ('option_two', models.TextField(max_length=250)),
                ('option_three', models.TextField(max_length=250)),
                ('option_four', models.TextField(max_length=250)),
                ('option_five', models.TextField(max_length=250)),
                ('question_slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('scq', 'Single Choice'), ('sqa', 'Text Answer')], default='scq', max_length=14)),
                ('brief_answer', models.TextField()),
                ('max_marks', models.IntegerField()),
                ('correct_options', models.CharField(max_length=150)),
                ('assesment_linked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assesments.Assesment')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_question_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_question_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assesments.question_set+', to='contenttypes.ContentType')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_question_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
