# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='duration_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assesment',
            name='duration_minutes',
            field=models.IntegerField(null=True),
        ),
    ]
