# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assesment',
            name='total_exam_duration',
        ),
    ]
