# Generated by Django 3.0.5 on 2020-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
