# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('assesments', '0002_auto_20171117_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('option_one', models.TextField(max_length=250)),
                ('option_two', models.TextField(max_length=250)),
                ('option_three', models.TextField(max_length=250)),
                ('option_four', models.TextField(max_length=250)),
                ('option_five', models.TextField(max_length=250)),
                ('opted_choice', models.TextField(max_length=250)),
                ('written_answer', models.TextField(max_length=250)),
                ('alloted_marks', models.FloatField(max_length=250)),
                ('question_slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('scq', 'Single Choice'), ('sqa', 'Text Answer')], default='scq', max_length=14)),
                ('brief_answer', models.TextField()),
                ('max_marks', models.IntegerField()),
                ('correct_options', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_answer_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_answer_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.IntegerField(default=10)),
                ('exam_taken_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time_taken', models.TimeField(null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('result_passed', models.BooleanField(default=False)),
                ('expired_on', models.DateTimeField()),
                ('type', models.CharField(default='result', editable=False, max_length=10)),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.Assesment')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_result_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_result_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assesments.result_set+', to='contenttypes.ContentType')),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('updated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_result_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='for_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.Result'),
        ),
        migrations.AddField(
            model_name='answer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assesments.answer_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assesments_answer_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
