# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0002_auto_20180829_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='privilege',
            field=models.CharField(choices=[(b'public', b'Public'), (b'private', b'Private')], default=b'private', max_length=14),
        ),
    ]
