# Generated by Django 3.0.5 on 2020-04-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0002_auto_20200422_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='written_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
