# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0002_remove_result_expired_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_slug',
        ),
    ]
