# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20171119_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Timing'),
        ),
    ]
