# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20180918_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
