# Generated by Django 3.0.5 on 2020-04-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20200422_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='privilege',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=14),
        ),
    ]
