# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 20:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0003_auto_20171113_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 20, 3, 59, 860762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 20, 3, 59, 860762, tzinfo=utc)),
        ),
    ]
