# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0004_auto_20171212_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='brief_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_options',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_five',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_four',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_three',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
