# Generated by Django 3.0.5 on 2020-05-02 18:24

import autoslug.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0004_auto_20200427_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=datetime.timedelta, editable=False, populate_from='header', unique=True),
            preserve_default=False,
        ),
    ]
