# Generated by Django 3.0.5 on 2020-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0006_assesment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='privilege',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('open', 'Open - Visible to Entire World')], default='public', max_length=14),
        ),
    ]
