# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0006_auto_20171113_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assesment',
            managers=[
                ('soft_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='total_question',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 20, 57, 5, 695530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 20, 57, 5, 695530, tzinfo=utc)),
        ),
    ]
