# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0007_auto_20171113_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
