# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assesments', '0008_auto_20171113_1258'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assesment',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_assesments.assesment_set+', to='contenttypes.ContentType'),
        ),
    ]
