# Generated by Django 3.0.5 on 2020-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200425_1014'),
        ('assesments', '0008_auto_20200504_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='subscriber_users',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
    ]
