# Generated by Django 3.0.5 on 2020-05-09 14:49

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0009_auto_20200509_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=django_quill.fields.QuillField(),
        ),
    ]
