# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesments', '0006_auto_20171213_1431'),
        ('assesments', '0009_auto_20171114_1237'),
    ]

    operations = [
    ]
