# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-09 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=45)),
                ('institute_contact_mobile', models.CharField(max_length=13)),
                ('institute_contact_landline', models.CharField(max_length=13, null=True)),
                ('institute_address', models.CharField(max_length=200)),
                ('institute_city', models.CharField(max_length=20)),
                ('institute_state', models.CharField(max_length=20)),
                ('institute_country', models.CharField(max_length=20)),
                ('institute_created', models.DateTimeField(auto_now_add=True)),
                ('institute_last_updated', models.DateTimeField(auto_now=True)),
                ('institute_password_last_updated', models.DateTimeField(auto_now_add=True)),
                ('institute_status', models.CharField(choices=[(b'inac', b'Inactive'), (b'acti', b'Active'), (b'pend', b'Pending'), (b'dele', b'Deleted')], default=b'pend', max_length=4)),
                ('user_type', models.CharField(default=b'institution', editable=False, max_length=11)),
                ('deleted', models.CharField(default=b'N', editable=False, max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Institute User Name')),
            ],
            options={
                'ordering': ('-institute_last_updated', '-institute_created'),
                'permissions': (('is_institute', 'Its an Institute'),),
            },
        ),
    ]
