# Generated by Django 3.0.5 on 2020-04-25 13:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='institute_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
