# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='institute_name',
            field=models.CharField(max_length=100),
        ),
    ]
