# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='deleted',
            field=models.CharField(default='N', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='institutions',
            name='user_type',
            field=models.CharField(default='institution', editable=False, max_length=11),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Institute User Name'),
        ),
    ]
